
SOCIAL_AUTH_TWITTER_KEY ='D9uo7DsldmnR5sTzye7sZhZ4t'
SOCIAL_AUTH_TWITTER_SECRET  = 'CIuY6EL9R1CwklncVsWaIjAoUYAWH9LxSfCpMt61M2G8R9vo4a'

SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/dashboard/'
SOCIAL_AUTH_LOGIN_URL = '/accounts/login/'