# Generated by Django 2.0.6 on 2018-07-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_watching_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='watching_accounts',
            name='twitter_profile_pic',
            field=models.CharField(default='https://x1.xingassets.com/assets/frontend_minified/img/users/nobody_m.original.jpg', max_length=250),
        ),
    ]
