# Generated by Django 2.0.6 on 2018-07-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_watching_accounts_twitter_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='watching_accounts',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
